### ISSUE TITLE
Typo in the `servicenow:now:table:retrieveRecords` action for scaffolder-backend

### ISSUE THREAD

**Issue by deshmukhmayur** [janus-idp/backstage-plugins#1012]
### Describe the bug

There's a typo in the servicenow-actions' retrieveRecords schema definition for the `sysparmQuery` ([retrieve-records.ts:27](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/servicenow-actions/src/actions/servicenow/now/table/retrieve-records.ts#L27)).

Due to this, the `sysparm_query` filter is not applied when using the `retrieveRecords` action.

### Expected Behavior

The field name should be `sysparmQuery`
```diff
- sysparamQuery
+ sysparmQuery
```

### What are the steps to reproduce this bug?

1. Install the servicenow-actions module and configure them up as per the [readme](https://github.com/janus-idp/backstage-plugins/tree/main/plugins/servicenow-actions#readme)
2. Create a template using the `servicenow:now:table:retrieveRecords` action

    <details>
    <summary>Example Template</summary>

    ```yaml
    apiVersion: scaffolder.backstage.io/v1beta3
    kind: Template
    metadata:
      name: template-name
    spec:
      owner: group:group-name
      type: service

      parameters:
        - title: Fill in some steps
          required:
            - name
          properties:
            name:
              title: Name
              type: string

      steps:
        - id: fetch-record
          name: Fetch Record from Example Table
          action: servicenow:now:table:retrieveRecords
          input:
            tableName: example-table
            sysparmQuery: name=${{ parameters.name }}
            sysparmLimit: 1

        - id: log
          name: Log Record
          action: debug:log
          input:
            message: ${{ steps['fetch-record'].output | dump(2) }}
    ```

    </details>

4. The action returns an error stating the `sysparmQuery` is not support.

### Versions of software used and environment

Package: `@janus-idp/backstage-scaffolder-backend-module-servicenow`
Version: `1.2.6`
