### ISSUE TITLE
[RBAC] Hide Edit Icon from users with no catalog-entity read permission

### ISSUE THREAD

**Issue by debsmita1** [janus-idp/backstage-plugins#1048]
### Describe the bug
RBAC UI List page and the Users and Groups card in the Role overview page shows the Edit icon to users with no access to read from the catalog entity. The Edit role form lists users and groups registered in the catalog. So logged-in users with no access to read from the catalog will not be able to associate members to any role. Hence they shouldn't be allowed to edit a role

### GIF

https://github.com/janus-idp/backstage-plugins/assets/22490998/eb95742f-92ec-41a7-a529-060c2569bf50

### What are the steps to reproduce this bug?
Install and configure RBAC backend and RBAC frontend plugin
app-config.yaml
```
permission:
  enabled: true
  rbac:
    admin:
      users:
        - name: <your logged in user name>
  ```

### Versions of software used and the environment
@janus-idp/backstage-plugin-rbac: 1.9.0
@janus-idp/backstage-plugin-rbac-backend: 2.0.0
