### ISSUE TITLE
Analytics Module: Matomo Analytics not tracking

### ISSUE THREAD

**Issue by fmartinezperez** [janus-idp/backstage-plugins#1058]
### Describe the bug

The plugin analytics-module-matomo was installed following the steps from README.md, but when the application is started is not tracking the information.

I have Matomo application running on docker using port 80.
I tried the Matomo script for tracking and in this case is working properly, and the log in the browser shows the requests to Matomo. But using the plugin is not.

Setup on Backstage:
![image](https://github.com/janus-idp/backstage-plugins/assets/148445843/38364ee0-4178-4709-9432-d06b49719241)

![image](https://github.com/janus-idp/backstage-plugins/assets/148445843/b4fd6ea9-a363-4081-ae2b-d2fd2411db37)

Setup on Matomo
![image](https://github.com/janus-idp/backstage-plugins/assets/148445843/05bc8f5e-7102-4fa9-ae3f-dd3f2aa462ee)

Logs from browser using script:
![image](https://github.com/janus-idp/backstage-plugins/assets/148445843/b8a99c89-aea9-41ad-99ba-f13e23a9cd8e)

### Expected Behavior

Application should show logs requesting to Matomo or an error if  was a connection problem.

### What are the steps to reproduce this bug?

1. Install the plugin on Backstage following the README.md
2. Matomo instance executing in local with docker.
3. Execute Backstage.

**Comment by fmartinezperez** [comment]
I found the problem.

Exists an error on README.md

```yaml
# app-config.yaml
app:
  analytics:
    matomo:
      instanceUrl: ${ANALYTICS_MATOMO_INSTANCE_URL}
      siteId: ${ANALYTICS_MATOMO_SITE_ID}
```

When it should be:

```yaml
# app-config.yaml
app:
  analytics:
    matomo:
      host: ${ANALYTICS_MATOMO_INSTANCE_URL}
      siteId: ${ANALYTICS_MATOMO_SITE_ID}
```
I found a pull [request ](https://github.com/janus-idp/backstage-plugins/pull/991)pending to be merged solving this error.

Close the issue.
