### ISSUE TITLE
[RBAC] Update the RBAC frontend plugin readme to add configuration to list permissions from other plugins

### ISSUE THREAD

**Issue by debsmita1** [janus-idp/backstage-plugins#1114]
### What do you want to improve?
- Update the RBAC frontend plugin readme to add configuration to include the permissions from other plugins
- Update the Readme to mention that default role:  **role:default/rbac_admin** wouldn't need to explicitly add catalog entity read permissions

### What does the current documentation state?
- It has no mention of how the permissions from other plugins (that this RBAC backend plugin [Readme](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/rbac-backend/docs/permissions.md) talks about) can be viewed in the Role creation form in the RBAC frontend plugin
- The readme says all users would need catalog entity read permissions

### What would you like to be added/updated in the documentation?

Add the following configuration to view permissions from plugins like Kubernetes and Jenkins

```
permission:
  enabled: true
  rbac:
    policies-csv-file: /rbac-policy.csv
    database:
      enabled: true
    pluginsWithPermission: 
      - kubernetes
      - jenkins
    admin:
      users:
        - name: user:default/xyz

```

```
p, role:default/team_a, catalog-entity, read, allow # only needed for users with the role other than `role:default/rbac_admin`
p, role:default/team_a, policy-entity, create, allow
g, user:default/<login-id/user-name>, role:default/team_a
```
