### ISSUE TITLE
RBAC - Backstage Backend fails to start with admins configured and database enabled

### ISSUE THREAD

**Issue by billabongrob** [janus-idp/backstage-plugins#1184]
### Describe the bug

Backend fails to start with admins configured and database enabled. 

Config is as follows: 
```
permission:
  enabled: true
  rbac:
    database:
      enabled: true
    admin:
      users:
        - name: user:default/xxxxx
        - name: user:default/xxxxx
        - name: user:default/xxxxx

```

### Expected Behavior

Backend starts.  Removing the admin, users portion does not start properly.  Errors show:
There are no admins configured for the RBAC-backend plugin. The plugin may not work properly.

### What are the steps to reproduce this bug?

1. Install plugins per documentation
2. Add the above
3. Cry into hands

### Versions of software used and environment

1.21.1 
```
"@janus-idp/backstage-plugin-rbac-backend@^2.1.3":
"@janus-idp/backstage-plugin-rbac-common@1.2.1":
"@janus-idp/backstage-plugin-rbac@^1.13.2":
```
