### ISSUE TITLE
🔌 Plugin: Not able to show custom plugin to in admin page drop down

### ISSUE THREAD

**Issue by ravimandalasapient** [janus-idp/backstage-plugins#1522]
### 🔖 Summary

I have added permission in app-config.yaml and enable the permission framework. But still, not showing custom plugin admin page plugin dropdown.Please let me know if anything i can add to enable that.
access-demo is my plugin id.
  
```
permission:
  enabled: true
  rbac:
    #policies-csv-file: ../../examples/rbac-policy.csv
    pluginsWithPermission:
        - acccess-demo
```
       

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ravimandalasapient** [comment]
Rbac plugin version is latest one.i.e 1.17.5.
acccess-demo is my custom plugin id(created front end & backend)

Indentation correct only.May be copy paste problem.

permission:
  enabled: true
  rbac:
    #policies-csv-file: ../../examples/rbac-policy.csv
    pluginsWithPermission:
        - acccess-demo
       

    admin:
      users:
        - name: user:default/ravimandalasapient
        - name: group:default/admins
    
    policies-csv-file: C:\Users\ravmanda1\NEOM\Projects\test-rbac-feature\cie-poc-developer-portal\examples\rbac-policies.csv

**Comment by ravimandalasapient** [comment]
permission:
  enabled: true
  rbac:
    #policies-csv-file: ../../examples/rbac-policy.csv
    pluginsWithPermission:
        - acccess-demo
       

    admin:
      users:
        - name: user:default/ravimandalasapient
        - name: group:default/admins
    
    policies-csv-file: C:\Users\ravmanda1\NEOM\Projects\test-rbac-feature\cie-poc-developer-portal\examples\rbac-policies.csv

**Comment by invincibleJai** [comment]
it's difficult to test/reproduce with plugin that we don't have access to. is it working for other community plugins i.e kubernetes , jenkins etc ? 


https://github.com/janus-idp/backstage-plugins/blob/main/plugins/rbac/README.md#installation

**Comment by ravimandalasapient** [comment]
@invincibleJai it is not working for any plugin(Kubernetes, Jenkins as well). I created simple plugin and tried. 
please, you can create any simple plugin and check.

**Comment by invincibleJai** [comment]
@ravimandalasapient i'll try to create a new plugin and test


@PatAKnight / @AndrienkoAleksandr do you see any obvious missing piece here ^^

**Comment by PatAKnight** [comment]
I am not seeing any immediate issues, but I will also take a look.

**Comment by invincibleJai** [comment]
@ravimandalasapient i did create a new plugins and verified it and it does work for me

<img width="1728" alt="image" src="https://github.com/janus-idp/backstage-plugins/assets/5129024/9055ec74-02ea-4c6d-8188-7cf9dac12dfb">

Can check the code here https://github.com/invincibleJai/todo-app-rbac

- make sure your plugin in enabled and it does define permissions
- make sure [pluginID](https://github.com/invincibleJai/todo-app-rbac/blob/main/plugins/todo-list-backend/src/plugin.ts#L30) and [route](https://github.com/invincibleJai/todo-app-rbac/blob/main/packages/backend/src/index.ts#L102) for backend plugins is same and it is used in config as below

```
permission:
  enabled: true
  rbac:
    pluginsWithPermission:
      - todolist
    policies-csv-file: /Users/jakumar/Workspaces/testBackstage/todo-app-rbac/rbac-policy.csv
    admin:
      users:
        - name: user:default/invincibleJai
```

Hope this could be helpful for you to figure out what wrong with your config or plugin.
