### ISSUE TITLE
[PLUGIN: ORCHESTRATOR] Getting issues while onboarding this plugin in backstage app

### ISSUE THREAD

**Issue by Alok650** [janus-idp/backstage-plugins#1698]
Hi guys,
I am trying to integrate the orchestrator plugin in my backstage app. I have onboarded it, but am getting logs about connection refused. I have followed the Readme of the plugin to integrate. The error message I am getting:

```
[1] 2024-05-21T13:18:41.218Z orchestrator debug Get workflow service urls result: {"operation":{"key":-10725952659,"query":{"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"ProcessDefinitions"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"serviceUrl"}}]}}]}}],"loc":{"start":0,"end":52,"source":{"body":"{\n  ProcessDefinitions {\n    id\n    serviceUrl\n  }\n}","name":"gql","locationOffset":{"line":1,"column":1}}},"__key":-10725952659},"variables":{},"kind":"query","context":{"url":"http://localhost:8080/graphql","requestPolicy":"cache-first","suspense":false}},"error":{"name":"CombinedError","graphQLErrors":[],"networkError":{"cause":{"errno":-61,"code":"ECONNREFUSED","syscall":"connect","address":"::1","port":8080}}},"hasNext":false,"stale":false} type=plugin
[1] 2024-05-21T13:18:41.219Z orchestrator error Error fetching workflow service urls [Network] fetch failed type=plugin
[1] 2024-05-21T13:18:41.219Z orchestrator error Error running task__Orchestrator__WorkflowCacheService: [Network] fetch failed type=plugin
```
my app-config.yaml configs for the plugin:

```
orchestrator:
  sonataFlowService:
    baseUrl: http://localhost
    port: 8080
    autoStart: true
    workflowsSource:
      gitRepositoryUrl: https://github.com/parodos-dev/backstage-orchestrator-workflows
      localPath: /tmp/orchestrator/repository
  dataIndexService:
    url: http://localhost:8080
```
I need to change the gitRepositoryUrl to keep my workflows. Also I have confusion regarding onboarding a new workflow in this plugin (currently the workflows on UI are empty). The new workflow I need to onboard needs to create a maker-checker (approval) mechanism using SAAS tools like JIRA tickets.
