### ISSUE TITLE
Users without email breaking all of the backend part and backstage fully crashes

### ISSUE THREAD

**Issue by jonatanask** [janus-idp/backstage-plugins#1709]
### Describe the bug

When imported users from gitlab doesn't have emails because their accounts are private, the system fully crashes and backstage stops working

`TypeError: Cannot read properties of undefined (reading 'email')
    at /app/node_modules/@janus-idp/backstage-plugin-feedback-backend/dist/cjs/plugin-DV3-jMW_.cjs.js:375:160
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

### Expected Behavior

If there is no email, just don't send email. Or possibility to not send emails and to not use jira. Just created feedbacks in database

### What are the steps to reproduce this bug?

1. When creating user kind, do not add email
```
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
  profile:
    displayName: Guest
```
2. Create a feedback with that user, for example guest
