### ISSUE TITLE
The pod ring text is misleading for DaemonSet resource

### ISSUE THREAD

**Issue by debsmita1** [janus-idp/backstage-plugins#197]
**Describe the bug**
The pod ring text on the DaemonSet resource node shows "Scaled to 0" when there are 2 pods running

**To Reproduce**
1. Create a DaemonSet resource with the below yaml:
```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: example
  labels:
    backstage.io/kubernetes-id: <entity-name>
spec:
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
        backstage.io/kubernetes-id: test-backstage
    spec:
      containers:
        - name: httpd
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
```
2. Wait for the pods to be up and running

**Expected behavior**
The pod ring text should show the correct pod info

**Screenshots**
![Screenshot 2023-03-23 at 4 53 30 PM](https://user-images.githubusercontent.com/22490998/227190380-fac20e31-c327-4b63-b86d-20ff0f86acdc.png)

**Additional context**
NA
