### ISSUE TITLE
🔌 Plugin: Keycloak backend plugin fails with Request failed with status code 504

### ISSUE THREAD

**Issue by rahulkandru** [janus-idp/backstage-plugins#2147]
### 🔖 Summary

Hi,

I followed the instructions [here ](https://janus-idp.io/plugins/keycloak)to setup the plugin. However, I keep running into the below issue -
 
```
 [0] webpack compiled successfully
[1] 2024-09-10T14:57:58.862Z catalog info Reading Keycloak users and groups class=KeycloakOrgEntityProvider taskId=KeycloakOrgEntityProvider:default:refresh taskInstanceId=55cb32b0-76b7-4c56-8b7b-48de0ac3b717
[1] 2024-09-10T14:58:16.224Z catalog error Error while syncing Keycloak users and groups Request failed with status code 504 class=KeycloakOrgEntityProvider taskId=KeycloakOrgEntityProvider:default:refresh taskInstanceId=55cb32b0-76b7-4c56-8b7b-48de0ac3b717 name=Error stack=Error: Request failed with status code 504
[1]     at createError (/home/rakandru/backstage/dev/node_modules/@keycloak/keycloak-admin-client/node_modules/axios/lib/core/createError.js:16:15)
[1]     at settle (/home/rakandru/backstage/dev/node_modules/@keycloak/keycloak-admin-client/node_modules/axios/lib/core/settle.js:17:12)
[1]     at IncomingMessage.handleStreamEnd (/home/rakandru/backstage/dev/node_modules/@keycloak/keycloak-admin-client/node_modules/axios/lib/adapters/http.js:322:11)
[1]     at IncomingMessage.emit (node:events:530:35)
[1]     at endReadableNT (node:internal/streams/readable:1696:12)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) status=504
[1] 2024-09-10T15:01:01.283Z catalog info Reading Keycloak users and groups class=KeycloakOrgEntityProvider taskId=KeycloakOrgEntityProvider:default:refresh taskInstanceId=9493a300-a4c9-48a8-b2cc-62bf94637141
[1] 2024-09-10T15:01:18.861Z catalog error Error while syncing Keycloak users and groups Request failed with status code 504 class=KeycloakOrgEntityProvider taskId=KeycloakOrgEntityProvider:default:refresh taskInstanceId=9493a300-a4c9-48a8-b2cc-62bf94637141 name=Error stack=Error: Request failed with status code 504
[1]     at createError (/home/rakandru/backstage/dev/node_modules/@keycloak/keycloak-admin-client/node_modules/axios/lib/core/createError.js:16:15)
[1]     at settle (/home/rakandru/backstage/dev/node_modules/@keycloak/keycloak-admin-client/node_modules/axios/lib/core/settle.js:17:12)
[1]     at IncomingMessage.handleStreamEnd (/home/rakandru/backstage/dev/node_modules/@keycloak/keycloak-admin-client/node_modules/axios/lib/adapters/http.js:322:11)
[1]     at IncomingMessage.emit (node:events:530:35)
[1]     at endReadableNT (node:internal/streams/readable:1696:12)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) status=504
```

My app-config.yaml - 
```
catalog:
  providers:
    keycloakOrg:
      default:
        # Remove the `/auth` if using keycloak 17+
        baseUrl: https://keycloak.domain
        clientId: backstage
        clientSecret: ${CLIENT_SECRET}
        loginRealm: test
        realm: test
        schedule:
          frequency:
            minutes: 30
          timeout:
            minutes: 3  # Customize this to fit your needs
          initialDelay:
            seconds: 15  # Customize this to fit your needs
          userQuerySize: 10
          groupQuerySize: 10
```

Keycloak version - 23.0.6
Backstage version - 1.30.0

I'm running in a new environment where I created a new app and updated the coded as per instructions - https://janus-idp.io/plugins/keycloak

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
