### ISSUE TITLE
Unify UX on how different plugins schedule workers/tasks

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#235]
**Description**
In each backend plugin we host in Janus-IDP, we offer a different mean to schedule workers. Not only when it comes how and where this is configured, but also how they are scheduled.

See and compare configuration for following plugins:
- 3Scale https://github.com/janus-idp/backstage-plugins/tree/main/plugins/3scale-backend#configure
- Keycloak https://github.com/janus-idp/backstage-plugins/tree/main/plugins/keycloak-backend#installation
- OCM https://github.com/janus-idp/backstage-plugins/tree/main/plugins/ocm#setup-janus-idpbackstage-plugin-ocm-backend

**Expected behavior**

I think 3Scale plugins provides the easiest method to configure the scheduler, please migrate the other plugins to this format:

```yaml
# app-config.yaml

catalog:
  providers:
    <PLUGIN_NAME>:
      <ENV>:
        schedule: # optional; same options as in TaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 1 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 1 }
```

**Acceptance Criteria**

- [x] Keycloak supports scheduler config through `app-config.yaml`
- [x] OCM supports scheduler config through `app-config.yaml`
