### ISSUE TITLE
Feature: OCM plugin: decouple backend auth from kuberentes plugin 

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#48]
**Is your feature request related to a problem? Please describe.**
Kuberentes plugin dependency may not be desired for multiple reasons:

- Adding a cluster to kubernetes plugin expects workload discovery on the cluster. If this is not permitted by a role, Backstage raises errors. Discovering workloads on the Hub cluster may not be desired.
- Accessing the Hub requires ServiceAccount access - it's accessed by the backend server at all times, therefore no identity provider can be used. That results in no RBAC applied, all users see the same/all data from the Hub cluster via Kuberentes plugin.

**Describe the solution you'd like**
Provide a different connection method. Consider changing the config schema to a partial of [`kubernetes-backend` cluster type](https://github.com/backstage/backstage/blob/38c306dc7f3ca9cf707dd768ac3c9b7fb5de6fd3/plugins/kubernetes-backend/config.d.ts#L37-L61):

```yaml
# app-config.yaml
ocm:
  # either use kubernetes
  name: # required if url not defined, string, current setup - match a cluster from kuberenetes plugin config
  # if name is not defined, use direct setup
  url: # required if name not defined, string, hub cluster api endpoint
  skipTLSVerify: # optional, bool, defaults to false
  skipMetricsLookup: # optional, bool, defaults to false
  caData: # optional, str, defaults to null
  caFile: # optional, str, defaults to null
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
