### ISSUE TITLE
Ansible: Populate the Backstage catalog with job templates from AAP instance

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-plugins#522]
**Description:** 

As a user, I would like to populate the Backstage catalog with job templates from the AAP instance

**Acceptance Criteria**

- [x] Create a backend plugin for AAP
- [x] User should be able to configure AAP instance with URL, token, etc
- [x] AAP plugin will populate the software catalog from the configured AAP instance

**Additional Info:**
Can take inspiration from 3scale-backend plugin and sample catalog can be seen below

```
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sampleJobTemplate
  title: Ansible Automation Job Template
  description: Job Templates allow for a set of parameters to be defined to run an Ansible Job.
  links:
    - url: https://docs.ansible.com/automation-controller/latest/html/userguide/job_templates.html
      title: Documentation
      icon: web
spec:
  type: ansible-job-template
  lifecycle: production
  owner: janus-authors
  system: janus-idp
```
