### ISSUE TITLE
Tekton and Topology: Prerequisites in documentation insufficient to view logs

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/backstage-plugins#667]
## What needs to be done
The current documentation for the Tekton and Topology plugin requires the user to create a Service Account for the Kubernetes plugin. It references the [Kubernetes RBAC section](https://backstage.io/docs/features/kubernetes/configuration/#role-based-access-control) in the backstage documentation, which does not mention the permissions required to display the pod logs.
![image](https://github.com/janus-idp/backstage-plugins/assets/50030060/bd63d803-f9fa-47c4-91b6-3e3cbbfc217d)

To remedy this, the user would also need to provide the following permission (specifically the `pods/log` permission) to the Service Account's `ClusterRole`:
```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-pod-logs
rules:
  # Base for Kubernetes plugin
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
     verbs:
      - get
      - list
```
