### ISSUE TITLE
Review the schedule frequency values proposed in the Readme for the  3Scale backend plugin

### ISSUE THREAD

**Issue by davidfestal** [janus-idp/backstage-plugins#914]
The 3Scale backend plugin Readme contains the following recommended scheduler settings: 

``` yaml
        schedule: # optional; same options as in TaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 1 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 1 }
```
Do we really want such settings ?

If we decide to change them, they should also be changed accordingly in the `app-config.yaml` file.

It might be a good idea to review such settings for other plugins as well.
