### ISSUE TITLE
[Tekton Plugin] Buttons in Pipeline Visualization sometimes are not fully contained in Brave Browser

### ISSUE THREAD

**Issue by Zaperex** [janus-idp/backstage-plugins#922]
### Describe the bug

When expanding the row in the tekton plugin to view the pipeline visualization, if there is only one task with a short name in the pipeline, the buttons in the pipeline visualization will not be fully contained by the box for the visualization. 

Observe the `test-pipeline-k8t4fa` pipeline with its `say-hello` task:
![image](https://github.com/janus-idp/backstage-plugins/assets/50030060/8e621163-e7a6-4583-acff-bb4357b81c59)

### Expected Behavior
The 4 buttons should be fully contained no matter the size of the task and number of tasks present in the pipeline run.
### What are the steps to reproduce this bug?

1. Install TektonCI component 
2. Configure Kubernetes backend plugin for tekton
3. Setup a pipeline run with a single task with a short name
    <details><summary>Example Pipeline</summary>
    
    ```yaml
    apiVersion: tekton.dev/v1beta1
    kind: Pipeline
    metadata:
      name: test-pipeline
      labels:
        backstage.io/kubernetes-id: backstage-showcase
    spec:
      tasks:
        - name: say-hello
          taskSpec:
            steps:
              - name: say-hello
                image: ubuntu
                script: |
                  #!/usr/bin/env bash
                  echo "Hello, World!"
    ```
    </details>
    <details><summary>Example Pipeline Run</summary>
    
    ```yaml
    apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: test-pipeline-run
      labels:
        backstage.io/kubernetes-id: backstage-showcase
    spec:
      pipelineRef:
        name: test-pipeline
    ```
    </details>

4. Trigger the pipeline run
5. Ingest a component into the entity with the correct annotations
6. Navigate to the CI tab and expand the row for the corresponding pipeline run

### Versions of software used and environment
janus-idp/backstage-plugin-tekton@3.1.3
Brave Browser [Version 1.60.118 Chromium: 119.0.6045.163 (Official Build) (64-bit)](https://brave.com/latest/)
