### ISSUE TITLE
[Tekton]: add `view sbom` and `view logs` actions column in the pipelineRun list page

### ISSUE THREAD

**Issue by karthikjeeyar** [janus-idp/backstage-plugins#988]
**Description:**

PipelineRun list page should contain the actions column at the right most end of the table.

Actions:
---
1.   `view SBOM` action (show this conditionally when a PipelineRun contains SBOM task)
2.  `View logs` action that opens the log viewer.

---

 **Additional notes:**

A valid SBOM task in the PipelineRun should contain following annotations and task results.
```
metadata:
 annotations: 
    task.output.location: results
    task.results.format: application/text
    task.results.type: external-link  # Optional: This will redirect to external page
    task.results.key: LINK_TO_SBOM
spec: …
status: 
    results:
       name: 'LINK_TO_SBOM'
       type: 'string'
       value: 'quay.io/repo/image:build-8e536-1692702836'


```

**Design:**

![image](https://github.com/janus-idp/backstage-plugins/assets/9964343/b24ff2f4-b4c2-47bd-b135-68a6b927e208)
