### ISSUE TITLE
[RBAC] Admin user configured doesn't have access to all permission policies by default

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-plugins#999]
### Describe the bug

When I simply add admins in the permission configuration as below and not policies in `rbac-policy.csv` as readme specify https://github.com/janus-idp/backstage-plugins/blob/main/plugins/rbac-backend/README.md#configure-policy-admins

```
permission:
 enabled: true
 rbac:
  admin:
   users:
    - name: user:default/<user>
```
    

then the admin only has access to `policy-entity` and not other plugin entities like `catalog-entity`

I explicitly need to specify each policy in `rbac-policy.csv` to get access to other plugin entities even for admin

`p, user:default/<user>, catalog.entity.read, use, allow`

### Expected Behavior

Admin should have access to all the permission policies by default

### What are the steps to reproduce this bug?

1. Setup backend plugin following https://github.com/janus-idp/backstage-plugins/blob/main/plugins/rbac-backend/README.md
2. add admins in the permission configuration as below in `app-config.yaml` and not policies in `rbac-policy.csv` as readme specify https://github.com/janus-idp/backstage-plugins/blob/main/plugins/rbac-backend/README.md#configure-policy-admins

```
permission:
 enabled: true
 rbac:
  admin:
   users:
    - name: user:default/<user>
```
3. start the instance
4. Admin users do not have access to Read/create a catalog and this may happen with other permission policy as well

### Versions of software used and environment

"@janus-idp/backstage-plugin-rbac-backend":  1.6.6
